spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/notification_db
    username: postgres
    password: QS1YR8URQ6

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

server:
  port: 8083