spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/order_db
    username: postgres
    password: QS1YR8URQ6

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: my-java-app-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

    # Опционально: включение виртуальных потоков Java 21 для обработки сообщений Kafka
    threads:
      virtual:
        enabled: true

server:
  port: 8082