spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/order_db
    username: postgres
    password: QS1YR8URQ6

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

    # Опционально: включение виртуальных потоков Java 21 для обработки сообщений Kafka
    threads:
      virtual:
        enabled: true

server:
  port: 8082