spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/inventory_db
    username: postgres
    password: QS1YR8URQ6

  jpa:
    hibernate:
      ddl-auto: update # validate
    show-sql: false

  grpc:
    client:
      channels:
        inventory:
          address: "localhost:9090"

server:
  port: 8081