syntax = "proto3";

option java_package = "com.underwearstore.inventoryservice.grpc"; // inventoryservice - смута
option java_multiple_files = true;

// запрос
message ProductRequest {
    int64 id = 1; // ID Product для проверки в БД
}

// ответ
message ProductResponse {
    int64 id = 1;
    string name = 2;
    bool available = 3; // есть ли Product с таким ID в БД
    int32 quantity = 4; // его количество
    string price = 5;
    int32 sale = 6;
}

// gRPC-сервис, который предоставляет наш микросервис
service InventoryService {
    // метод проверки наличия товара
    rpc CheckAvailability(ProductRequest) returns (ProductResponse);
}
